import { init as initAnimations } from './modules/animations.js';
import { init as initUiState } from './modules/ui-state.js';
import { init as initCatalog } from './modules/catalog.js';
import { init as initCatalogFilterPopup } from './modules/catalog-filter-popup.js';
import { init as initHero } from './modules/hero.js';
import { init as initActivityPicker } from './modules/activity-picker.js';
import { init as initRecommendations } from './modules/recommendations.js';
import { init as initGiftCards } from './modules/gift-cards.js';
import { init as initBuildKit } from './modules/build-kit.js';
import { init as initCart } from './modules/cart.js';
import { init as initStories } from './modules/stories.js';
import { init as initProduct } from './modules/product.js';
import { init as initShared } from './modules/shared.js';
import { init as initPersonal } from './modules/personal.js';
import { init as initReviews } from './modules/reviews.js';
import { init as initLoyalty } from './modules/loyalty.js';

document.addEventListener('DOMContentLoaded', () => {
  initAnimations();
  initUiState();
  initCatalog();
  initCatalogFilterPopup();
  initHero();
  initActivityPicker();
  initRecommendations();
  initGiftCards();
  initBuildKit();
  initCart();
  initStories();
  initProduct();
  initShared();
  initPersonal();
  initReviews();
  initLoyalty();
});
